<?php

// Generated by GenAI\Container\Util\Dumper - do not edit by hand.
// Returns a Closure that populates a GenAI\Container\Container.
// require this file, then call the Closure with your container.

return function (\GenAI\Container\Container $c) {
    $c->register('Demo\\Greeter', function (\GenAI\Container\Container $c) {
        return new \Demo\Greeter($c->get('Demo\\Clock'), 'PujaCMS', 'Hi');
    });
    $c->register('Demo\\AppConfig', function (\GenAI\Container\Container $c) {
        return new \Demo\AppConfig();
    });
    $c->register('Demo\\Mailer', function (\GenAI\Container\Container $c) {
        return $c->get('Demo\\AppConfig')->mailer($c->get('Demo\\Clock'));
    });
    $c->register('Demo\\Clock', function (\GenAI\Container\Container $c) {
        return new \Demo\Clock();
    });
    $c->register('Demo\\UserRepository', function (\GenAI\Container\Container $c) {
        return new \Demo\UserRepository();
    });
};
